---
lh_loc_dir: /home/user/appserv/lighthouse
lh_acc_log_name: lighthouse_access
lh_vcs: https://github.com/VKCOM/lighthouse.git
ls_url: http://localhost
cl_url: http://localhost:8123
cl_user: user
ls_loc_install: false
nginx_user_name: user

