---
all:
  hosts:
    sonar-01:
      ansible_connection: ssh
      ansible_host: 178.154.220.228
    nexus-01:
      ansible_connection: ssh
      ansible_host: 178.154.223.167
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
