{
 "title": "Test_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\",fstype=\"vfat\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda5\",fstype=\"ext4\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"tmpfs\",fstype=\"tmpfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m]))*100)"
    }
   ]
  }
 ]
}