all:
  hosts:
    master:
      ansible_host: 192.168.1.33
      ip: 192.168.1.33
      access_ip: 192.168.1.33
    node1:
      ansible_host: 192.168.1.18
      ip: 192.168.1.18
      access_ip: 192.168.1.18
    node2:
      ansible_host: 192.168.1.14
      ip: 192.168.1.14
      access_ip: 192.168.1.14
    node3:
      ansible_host: 192.168.1.12
      ip: 192.168.1.12
      access_ip: 192.168.1.12
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
