version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
  - package-ecosystem: "gomod"
    directory: "/.ci/providerlint"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/.ci/tools"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/skaff"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/repository"
    schedule:
      interval: "daily"
