---

- name: create certs dir
  file: dest={{ssl_certs_path}}/certs state=directory mode=0700
  when: ssl_certs_path is defined

- name: copy certs
  copy: src='files/certs/{{project}}/{{client}}/{{env}}/{{item}}' dest='{{ssl_certs_path}}/{{item}}' owner=root mode=0440
  with_items:
    - '{{ssl_cert}}'
    - '{{ssl_key}}'
  when: ssl_cert is defined and ssl_key is defined and ca_ssl_cert is undefined

- name: config_nginx | configuring nginx place nginx.conf
  template:
    src: "config/{{env}}/balancers/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  become: true

- name: config_nginx | configuring nginx custom configs
  template:
    src: "config/{{env}}/balancers/conf.d/{{item}}.j2"
    dest: "/etc/nginx/conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  become: true
  with_items:
    - "{{nginx_config_files}}"

- name: config_nginx | start systemd unit
  systemd:
    name: 'nginx'
    state: started
    enabled: yes
    daemon_reload: yes