server_name: news-app-demo
access_log: /var/log/nginx/access.log main
error_log: /var/log/nginx/error.log warn
exclude_node: nothing

nginx_official_repo_mainline: true

nginx_config_files:
  - news-app.conf

upstreams:
  news-app:
    name: news-app
    options:
      - keepalive 50
    servers:
      - 127.0.0.1:8080 max_fails=10 fail_timeout=10s

locations:
  root:
    name: /
    options:
      - proxy_set_header    Host                $host
      - proxy_set_header    X-Real-IP           $remote_addr
      - proxy_set_header    X-Forwarded-Host    $host
      - proxy_set_header    X-Forwarded-Server  $host
      - proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for
      - proxy_redirect      off
      - proxy_next_upstream error timeout http_502 http_503 http_500 http_504 non_idempotent
      - proxy_next_upstream_tries 2
    proxy_pass: http://news-app
