---
- name: Download Nginx
  become: true
  ansible.builtin.get_url:
    url: "https://nginx.org/packages/centos/7/x86_64/RPMS/nginx-{{ nginx_version }}-1.el7.ngx.x86_64.rpm"
    dest: "./nginx-{{ nginx_version }}-1.el7.rpm"
- name: Install Nginx
  become: true
  ansible.builtin.yum:
    name: "nginx-{{ nginx_version }}-1.el7.rpm"
- name: NGINX | Create general config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0755
  notify: reload-nginx

