---
- name: Lighthouse - Create lh config
  become: true
  template:
    src: "templates/default.conf.j2"
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: reload-nginx
- name: Lighthouse - Copy git
  git:
    repo: "{{ lh_vcs }}"
    version: master
    dest: "{{ lh_loc_dir }}"
  register: copy_remote
