name: Autoremove Labels

on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]

jobs:
  RemoveTriagingLabelsFromClosedIssueOrPR:
    runs-on: ubuntu-latest
    steps:
      - name: Remove triaging labels from closed issues and PRs
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            needs-triage
            waiting-response
