on:
  - pull_request_target

name: Pull Request Target (All types)

env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply Labels
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler-pr-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  NeedsTriageLabeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply needs-triage Label
        uses: actions/labeler@v4
        if: github.event.action == 'opened' && env.IN_MAINTAINER_LIST == 'false'
        with:
          configuration-path: .github/labeler-pr-needs-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  SizeLabeler:
    runs-on: ubuntu-latest
    steps:
      # See also: https://github.com/CodelyTV/pr-size-labeler/pull/26
      - name: Apply Size Label
        uses: bflad/pr-size-labeler@d56e9ca5fe93539a256a7e7b4efd971f4f19fe00
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '60'
          m_label: 'size/M'
          m_max_size: '150'
          l_label: 'size/L'
          l_max_size: '300'
          xl_label: 'size/XL'
          message_if_xl: ''
  PullRequestComments:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to add helpful context for new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Welcome @${{github.actor}} :wave:

            It looks like this is your first Pull Request submission to the [Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws)! If you haven’t already done so please make sure you have checked out our [CONTRIBUTOR](https://hashicorp.github.io/terraform-provider-aws/) guide and [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) to make sure your contribution is adhering to best practice and has all the necessary elements in place for a successful approval.

            Also take a look at our [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) which details how we prioritize Pull Requests for inclusion.

            Thanks again, and welcome to the community! :smiley:
