## These checks will be superseded by documentation.yml
## when the provider documentation layout is moved to
## the Terraform Registry layout.
name: Website Checks
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/website.yml
      - .go-version
      - .ci/.markdownlinkcheck.json
      - .ci/.tflint.hcl
      - .markdownlint.yml
      - website/docs/**
      - tools/go.mod

jobs:
  markdown-link-check-a-h-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YakDriver/md-check-links@v2.0.5
        name: markdown-link-check website/docs/**/[a-h].markdown
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".ci/.markdownlinkcheck.json"
          folder-path: "website/docs"
          file-prefix: "[a-h]"
          file-extension: ".markdown"
          base-branch: "main"
          check-modified-files-only: "no"
  markdown-link-check-i-z-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YakDriver/md-check-links@v2.0.5
        name: markdown-link-check website/docs/**/[i-z].markdown
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".ci/.markdownlinkcheck.json"
          folder-path: "website/docs"
          file-prefix: "[i-z]"
          file-extension: ".markdown"
          base-branch: "main"
          check-modified-files-only: "no"
  markdown-link-check-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: YakDriver/md-check-links@v2.0.5
        name: markdown-link-check website/docs/**/*.md
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".ci/.markdownlinkcheck.json"
          folder-path: "website/docs"
          file-extension: ".md"
          base-branch: "main"
          check-modified-files-only: "yes"
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: "website/docs"
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell
      - run: misspell -error -source text website/
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: terrafmt diff ./website --check --pattern '*.markdown'
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt

      - run: cd .ci/tools && go install github.com/terraform-linters/tflint

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}

      - run: tflint -c .ci/.tflint.hcl --init

      - run: |
          exit_code=0

          # Configure the rules for tflint.
          # The *_invalid_* rules disabled here prevent evaluation of expressions.
          # Do not disable *_invalid_name rules, since these are good checks for e.g. "%s" formatting verbs
          # being carried over from test cases.
          shared_rules=(
              "--enable-rule=terraform_comment_syntax"
              "--disable-rule=aws_cloudwatch_event_target_invalid_arn"
              "--disable-rule=aws_db_instance_default_parameter_group"
              "--disable-rule=aws_elasticache_cluster_default_parameter_group"
              "--disable-rule=aws_elasticache_replication_group_default_parameter_group"
              "--disable-rule=aws_iam_policy_sid_invalid_characters"
              "--disable-rule=aws_iam_saml_provider_invalid_saml_metadata_document"
              "--disable-rule=aws_iam_server_certificate_invalid_certificate_body"
              "--disable-rule=aws_iam_server_certificate_invalid_private_key"
              "--disable-rule=aws_lb_invalid_load_balancer_type"
              "--disable-rule=aws_lb_target_group_invalid_protocol"
              "--disable-rule=aws_transfer_ssh_key_invalid_body"
              "--disable-rule=aws_worklink_website_certificate_authority_association_invalid_certificate"
              "--disable-rule=aws_iot_certificate_invalid_csr"
              "--disable-rule=aws_networkfirewall_rule_group_invalid_rules"
              "--disable-rule=aws_appsync_function_invalid_request_mapping_template"
              "--disable-rule=aws_appsync_function_invalid_response_mapping_template"
              "--disable-rule=aws_appsync_resolver_invalid_request_template"
              "--disable-rule=aws_appsync_resolver_invalid_response_template"
              "--disable-rule=aws_servicecatalog_portfolio_share_invalid_type"
              "--disable-rule=aws_s3_object_copy_invalid_source"
          )
          while read -r filename; do
            rules=("${shared_rules[@]}")
            if [[ "$filename" == "./website/docs/guides/version-2-upgrade.html.md" ]]; then
                # ./website/docs/guides/version-2-upgrade.html.md should still include pre-0.12 syntax,
                # since v1.0 does not support Terraform 0.12.
                rules+=(
                "--disable-rule=terraform_deprecated_interpolation"
                "--disable-rule=terraform_deprecated_index"
                )
            elif [[ "$filename" == "./website/docs/guides/version-3-upgrade.html.md" ]]; then
                # ./website/docs/guides/version-3-upgrade.html.md has one example showing migration from
                # pre-0.12 syntax to 0.12 syntax. We can't customize rules per block, and adding a
                # tflint-ignore directive to documentation is not ideal.
                rules+=(
                "--disable-rule=terraform_deprecated_interpolation"
                "--enable-rule=terraform_deprecated_index"
                )
            else
                rules+=(
                "--enable-rule=terraform_deprecated_interpolation"
                "--enable-rule=terraform_deprecated_index"
                )
            fi

            # We need to capture the output and error code here. We don't want to exit on the first error
            set +e
            ./.ci/scripts/validate-terraform-file.sh -c .ci/.tflint.hcl "$filename" "${rules[@]}"
            lint_exitcode=$?
            set -e
            if [ $lint_exitcode -ne 0 ]; then exit_code=1; fi
          done < <(find ./website/docs -type f \( -name '*.md' -o -name '*.markdown' \) | sort -u)

          exit $exit_code
