---
# defaults file for nginx
config_nginx: true
nginx_worker_processes: 'auto'
nginx_enable_ipv6: false
nginx_access_log: '/var/log/nginx/access.log'
nginx_access_log_web: '/var/log/nginx/access_web.log'
nginx_error_log: '/var/log/nginx/error.log'
nginx_events_block:
  - 'multi_accept on'
  - 'worker_connections 65535'

# custom headers
nginx_headers: []
  # - 'set_real_ip_from 192.168.250.0/24'
  # - 'real_ip_header X-Real-IP'
  # - 'real_ip_recursive on'

nginx_http_block:
  basic_settings:
    - 'keepalive_timeout 65'
    - 'charset utf-8'
    - 'sendfile on'
    - 'server_names_hash_bucket_size 128'
    - 'server_name_in_redirect off'
    - 'server_tokens off'
    - 'tcp_nodelay on'
    - 'tcp_nopush on'
    - 'log_not_found off'
    - 'types_hash_max_size 2048'
    - 'include /etc/nginx/mime.types'
    - 'default_type application/octet-stream'
#    - 'open_file_cache max=200000 inactive=20s'
#    - 'open_file_cache_valid 30s'
#    - 'open_file_cache_min_uses 2'
#    - 'open_file_cache_errors on'
    - 'keepalive_requests 1000'
    - 'reset_timedout_connection on'
    - 'client_body_timeout 10'
    - 'client_max_body_size 100m'
    - 'send_timeout 2'
    - 'etag on'
#    - 'limit_req_zone $binary_remote_addr zone=requests:10m rate=20r/s'
#    - 'limit_req zone=requests burst=40'


  gzip_settings:
    - 'gzip on'
    - 'gzip_disable "msie6"'
    - 'gzip_vary on'
    - 'gzip_proxied any'
    - 'gzip_comp_level 6'
    - 'gzip_buffers 16 8k'
    - 'gzip_http_version 1.1'
    - 'gzip_types text/plain text/css application/json application/javascript application/xml application/xml+rss text/javascript application/x-javascript text/xml'
  ssl_settings:
    - 'ssl_session_timeout 1d'
    - 'ssl_session_cache shared:SSL:10m'
    - 'ssl_session_tickets off'
    - 'ssl_dhparam /etc/nginx/dhparam.pem'
    - 'ssl_protocols TLSv1.2 TLSv1.3'
    - 'ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
  logging_settings:
    - "log_format parsing '$time_local|$msec|$server_name|$status|$remote_addr|$request|$body_bytes_sent|-|$http_referer|$http_user_agent|$request_time|$http_x_real_ip|$http_x_forwarded_for|($upstream_addr|$upstream_response_time|$upstream_status)'"
    - 'access_log {{ nginx_access_log }} parsing'
    - 'error_log {{ nginx_error_log }}'
  vhost_configs:
    - 'include /etc/nginx/conf.d/*.conf'
#    - 'include /etc/nginx/sites-enabled/*'
nginx_listen_port: 80

nginx_default_sites_block:
    - 'server_name _;'
    - 'access_log /dev/null;'
    - 'error_log /dev/null;'
    - 'location /status {'
    - 'vhost_traffic_status_bypass_limit on;'
    - 'vhost_traffic_status_bypass_stats on;'
    - 'vhost_traffic_status_display;'
    - 'vhost_traffic_status_display_format prometheus;'
    - '}'
